### ISSUE TITLE
Bridge.global.System conflicts with systemjs System

### ISSUE THREAD

**Issue by alexanderzobnin** [Azure/monaco-kusto#22]
### Description

`Bridge.global.System` conflicts with systemjs `System`.
In `kustoLanguageService.ts` `System` accessed as a global variable. This causes conflict with systemjs `System` variable and this code fails
https://github.com/Azure/monaco-kusto/blob/master/src/languageService/kustoLanguageService.ts#L37
```ts
let List = System.Collections.Generic.List$1;
```
with error `TypeError: Cannot read property 'Generic' of undefined`.
I found that older version accesses `System` through the `Bridge` variable:
```js
var List = Bridge.global.System.Collections.Generic.List$1;
```
and it works. 
This may be fixed either by accessing through the `Bridge` variable or by redeclaring `System` variable, like:
```ts
let System = (Bridge.global as any).System;
```

 ### System configuration

 monaco-editor version: 0.2.2 (master)
 Browser: Chrome
 OS: Linux

**Comment by alexanderzobnin** [comment]
It seems, it's similar to https://github.com/bridgedotnet/Bridge/issues/3097

**Comment by mrosack** [comment]
It would be awesome if there was a way to rename the System namespace from a setting in the bridge.json.  I'm using code transpiled by Bridge.Net inside of an Angular 7 project - we have common frontend/backend C# business logic that we use Bridge to transpile and include inside of Angular, but we're forced to massage the output after compilation to get it to work with Angular because of this issue.  What we do is just blindly rename `System` to `Syst3m` in our afterBuild script, like this:

```
powershell -Command "(gc %veTs%) -replace 'System', 'Syst3m' | Out-File -Encoding 'UTF8' %veTs%"
powershell -Command "(gc %bTs%) -replace 'System', 'Syst3m' | Out-File -Encoding 'UTF8' %bTs%"
powershell -Command "(gc %veJs%) -replace '//# sourceMappingURL=data:application/json;base64', \"Syst3m = System;`n`n//# sourceMappingURL=data:application/json;base64\" | Out-File -Encoding 'UTF8' %veJs%"
```

Where `veTs` is our custom type definitions, `bTs` is the bridge type definitions, and `veJs` is the full javascript output with `combineScripts` set to true.  But it'd be great if we didn't need to do this. 😄

**Comment by maxburs** [comment]
Closing as stale. If anyone is still experiencing this, please add a comment and I'll re-open this issue.
